
#url加入/api的前缀
spring.mvc.pathmatch.use-suffix-pattern=true
server.servlet.context-path=/api/


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=root
spring.datasource.password=123

#使用以下方式，完成较简单的配置
#mybatis.mapper-locations=classpath:mapping/*Mapper.xml
#mybatis.type-aliases-package=cn.johnyu.pojo

# 使用传统的MyBatis的配置
mybatis.config-location=classpath:mybatis-config.xml